<?php $email_addresses = implode(',', PL_Lead_Capture_Helper::get_lead_forwarding_addresses()) ?>
<?php echo PL_Helper_Header::pl_settings_subpages(); ?>
	<div class="settings_option_wrapper">
		<?php echo PL_Router::load_builder_partial('admin-box-top.php', array('title' => 'Email Forwarding')); ?>
			<p>Email forwarding will bcc all leads generated by your Placester site to one or many email addresses you specify. It is a great way to send your leads to third party CRMs. Enter the email addresses below.</p>
			<span id="email_validation" class="email_validation"></span>
			<div class="form-row">
				<div style="display: none" class="pls-loading-overlay"></div>
				<label for="">Email addresses, separated by commas, where leads should be forwarded to:</label>
				<div class="clear"></div>
				<textarea class="full-size" name="send_client_message_text" id="forwarding_email_addresses" cols="30" rows="10" ><?php echo $email_addresses ?></textarea>
				<div class="message_keywords">
					<p>Tips on how to use this:</p>
					<ul>
						<li>Enter email addresses only</li>
						<li>Enter your email addresses separated by a comma. </li>
						<li>Enter as many email addresses as you'd like</li>
					</ul>
				</div>
			</div>
			<div class="form-row">
				<input type="submit" id="button_email_forwarding" class="button-primary" value="Save">
			</div>
		<?php echo PL_Router::load_builder_partial('admin-box-bottom.php'); ?>
	</div>
